language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t friscop3t3/react-test  -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true friscop3t3/react-test npm test -- --coverage

after_success:
  - docker build -t friscop3t3/multi-client ./client
  - docker build -t friscop3t3/multi-nginx ./nginx
  - docker build -t friscop3t3/multi-server ./server
  - docker build -t friscop3t3/multi-worker ./worker
# push the images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push friscop3t3/multi-client
  - docker push friscop3t3/multi-nginx
  - docker push friscop3t3/multi-server
  - docker push friscop3t3/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-542906812955
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
